scrape_configs:
  - job_name: 'kafka-exporter' # job_name 은 모든 scrap 내에서 고유해야함
    scrape_interval: 10s      # global에서 default 값을 정의해주었기 떄문에 안써도됨
    scrape_timeout: 10s       # global에서 default 값을 정의해주었기 떄문에 안써도됨
    scheme: 'http'            # 옵션 - request를 보낼 scheme 설정 | default = http

    # 실제 scrap 하는 타겟에 관한 설정
    static_configs:
      - targets: ['kafka-exporter:9308'] ## prometheus, node-exporter, cadvisor